Exception: Error occurred because of time out
# stdout = above, stderr = none, ret = 1.  I suspect there will be several timeout messages, hence this is called timeout1
